version: "3"
services:
  nas-tools:
    build:
      # 构建上下文为仓库根目录
      context: .
      dockerfile: docker/Dockerfile.source
      args:
        - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple   # 国内网络加速，海外可注释本行
        #- ALPINE_MIRROR=mirrors.ustc.edu.cn                      # 国内网络加速，海外可注释本行
        #- REPO_URL=https://github.com/minquejoe/nas-tools-hsuyelin.git  # 容器内在线更新的代码来源，默认为本仓库
    image: nas-tools:source
    ports:
      - 3000:3000        # 默认的webui控制端口
    volumes:
      - ./config:/config   # 冒号左边请修改为你想保存配置的路径
      - /你的媒体目录:/你想设置的容器内能见到的目录   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment:
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      # 在线更新/自动更新的代码来源（https协议），默认已在镜像内设置为本仓库
      #- REPO_URL=https://github.com/minquejoe/nas-tools-hsuyelin.git
      - NASTOOL_AUTO_UPDATE=false  # 设置为true时，容器每次启动自动从REPO_URL拉取最新代码并重启；false时可通过webUI"在线更新"手动升级
      - NASTOOL_CN_UPDATE=true     # 国内网络更新依赖时使用国内源加速
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
